name: Release

on:
  workflow_call:

jobs:

  release_package:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: ./.venv
        key: venv-${{ github.run_id }}

    - name: Touch dev environment
      run: make touch-dev

    - name: Build package
      run: make release

    - name: Release package
      run: python -m twine upload -u "__token__" -p "${{ secrets.PYPI_API_TOKEN }}" dist/*.tar.gz  dist/*.whl
      if: ( github.event_name == 'release' && github.event.action == 'published' )
    
    - name: Upload package
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        gh release upload ${{ github.event.release.tag_name }} dist/*.tar.gz  dist/*.whl --clobber
      if: ( github.event_name == 'release' && github.event.action == 'published' )
